### ISSUE TITLE
Reset cache on multiple instance

### ISSUE THREAD

**Issue by GregoireW** [helaili/github-oidc-auth-app#11]
Let say I want to have a scale minimum to 2 on this service. 
The webhook will trigger a cache reloading on 1 instance not the 2. 

I see 3 ways resolving this problem:
- use an external tools to cache the policies 
- use an external messaging tool to push a "reload" message listened by all the instance
- create a reload endpoint and make the instance receiving the event to trigger reload on all other instance via a call to the api. Instance resolution could be done via a DNS resolution for instance (headless service on kubernetes, entry in dns with a server pool... ) 

A dns solution would be like this:

`````
if os.GetEnv("INSTANCES_LIST")!=nil {
        context := context.Background()
	res, err := net.DefaultResolver.LookupIP(context, "ip", os.GetEnv("INSTANCES_LIST"))
	if err != nil {
		log.Fatalf("No ip found for the given instance list %s", os.GetEnv("INSTANCES_LIST"), err)
	}
	for _, ip := range res {
		// Call the /resetCache endpoint to reset the cache
		_, err := http.Post(fmt.Sprintf("http://%s/resetCache", ip.String()), "application/json", nil)
		if err != nil {
			log.Fatalf("Instance with IP %s is in error", ip, err)
		}
	}
}
```

any thought on this ?

**Comment by helaili** [comment]
With the most recent version, caching is achieved in memory locally on each node and refreshed when a pushed event related to the config file is received, or upon an installation lifecycle event (install, suspend, unsuspend, remove). 

At this time I don't know that there will be massive node deployment with large config requiring a clever caching mechanism, so I'll keep it simple for now. I'm really interested in moving to a repo based config though in order to be able to leverage `CODEOWNERS` and also some safety check workflows.

**Comment by helaili** [comment]
This is not exactly how it works. Let me try to explain better:

`OrgA` is exposing resources and permissions through an app installation. This org has one single config file that lists all the contexts in which it will provide customised access to 3rd party orgs (`OrgB`, `OrgC`...). That means the caching mechanism only need to handle one config file per installation of a GitHub App deployment. If your enterprise account has 10 orgs and those need to access resources in only two of them, you could either have:
- 1 GitHub App with 2 installations: 2 config files need to be managed by the runtime. 
- 2 GitHub Apps with 1 installation each: 1 config file needs to be managed by each runtime. 

Now with the same principle in mind (1 centralised config per installation) I would like to replace the single file in a repo by a dedicated repo with multiple files, so that the approval mechanism can be further customised. Below is the structure I'm thinking about.

- Entries with a `.json` extension are files, the others are folders. 
- Each folder allows to sort of set a constant for all the files underneath and it cannot be overridden. 
- This repo will be in `OrgA` which has at least 2 repositories: `codespace-oddity` and `commit-on-mars`.
- Access to `OrgA/codespace-oddity` from anywhere within org `Ziggy-Stardust` will be defined in files `file3.json` and `file4.json` 
- Access to `OrgA/codespace-oddity` from anywhere within repo `Ziggy-Stardust/starman` will be defined in files `file5.json` and `file6.json` 
- Access to `OrgA/codespace-oddity` from the `production` environment within repo `Ziggy-Stardust/starman` will be defined in files `file7.json` and `file8.json` 
- Access to `OrgA/codespace-oddity` from a `production` environment within org `Ziggy-Stardust` will be defined in files `file17.json` and `file18.json` 
- Organisation level permissions will be defined in a separate but similar folder structure.
- Each file will have a different schema based on its location in the folder hierarchy, so that we can validate through PR checks that no excessive permissions are being granted. 

```yaml
file1.json
file2.json
repositories:
  - codespace-oddity:
    - owners:
      - Ziggy-Stardust:
        - file3.json
        - file4.json
        - repositories: 
          - starman:
             - environments: 
                - production:
                  - file7.json
                  - file8.json  
            - file5.json
            - file6.json
        - environments: 
          - production:
            - file17.json
            - file18.json  
  - commit-on-mars:
    - owners:
     ....   
organisation:
  - file9.json
  - file10.json
  - owners:
      - Ziggy-Stardust:
        - file11.json
        - file12.json
        - repositories: 
          - starman:
            - file13.json
            - file14.json
        - environments: 
          - production:
            - file15.json
            - file16.json
```
